Verificacion de Email
cess15/grupo-1-control-asistencias pull request #13
Opened 2021-03-05 16:06 UTC by cess15

* Diseño del template para verificar cuenta
* Envio de correo electronico para verificar cuenta
* Se cambio el estado al registrar un profesor, el estado de usuario esta por defecto en
  false
* Generacion de UUID aleatorio para verificar cuenta, una vez verificado
  se cambia el estado de usuario a true y podrá acceder al sistema
* Implementación de cambio de foto de perfil y método para borrar
  archivos del directorio despues de subir a Firebase
* Se agrego un campo verification_token al modelo Profesor y a la base de datos

2021-03-05 17:12 UTC, jorgdz approved these changes, later dismissed

2021-03-05 17:12 UTC, jorgdz commented on src/main/java/com/istb/app/services/profesor/ProfesorServiceImpl.java
> +		Profesor profesorGuarded = profesorRepository.save(profesor);
¿y cuando le llega el correo de verificación, como sabe el docente cuál es su clave?

2021-03-05 19:41 UTC, cess15 commented on src/main/java/com/istb/app/services/profesor/ProfesorServiceImpl.java
> +		Profesor profesorGuarded = profesorRepository.save(profesor);
Es una muy buena pregunta, voy a realizar las respectivas correcciones

2021-03-05 19:43 UTC, Elsorbo requested changes
Buen trabajo al documentar cosas como la adición del campo `verification_token` y el cambio del `estado` en la entidad `Usuario`. Una recomendación adicional es que pongas porque en lugar de solo que. El que cambiaste ayuda a buscar rapido el cambio, pero el porque, explica las razones y ayuda a entender el contexto del cambio.

2021-03-05 19:43 UTC, Elsorbo commented on src/main/java/com/istb/app/controller/VerificationController.java
> +			Usuario usuario = userService.findById(profesor.getUsuario().getId());
Para evitar la consulta utiliza el usuario de la instancia *profesor*
```suggestion
			Usuario usuario = profesor.getUsuario();
```

2021-03-05 19:43 UTC, Elsorbo commented on src/main/java/com/istb/app/api/controller/user/UserApiController.java
> +		usuario.setImagenPerfil(fileUpload.getName());
Deberias borrar la imagen antigua de firebase antes de actualizar a la nueva.
```suggestion
		fbmanager.delete( usuario.getImagenPerfil() );
		usuario.setImagenPerfil(fileUpload.getName());
```

2021-03-05 19:43 UTC, Elsorbo commented on src/main/java/com/istb/app/services/profesor/ProfesorServiceImpl.java
>  		Profesor existeCorreo = profesorRepository.findByCorreoAndIdIsNot(profesor.getCorreo(), id);
Aqui podrias utilizar un boolean, adicionalmente para que no trates con valores `null` podrias utilizar un objeto `Optional` de tipo `Profesor` en el método del repositorio.

```suggestion
		boolean existeCorreo = profesorRepository.findByCorreoAndIdIsNot(
		    profesor.getCorreo(), id ).get().isPresent();
```
El cambio en [ProfesorService](https://github.com/cess15/grupo-1-control-asistencias/blob/feature-email-verify/src/main/java/com/istb/app/repository/ProfesorRepository.java) seria:
`Optional<Profesor> findByCorreoAndIdIsNot(String correo, int id);`

2021-03-05 19:43 UTC, Elsorbo commented on src/main/java/com/istb/app/services/profesor/ProfesorServiceImpl.java
>  		if (existeCorreo != null) {
Con el cambio descrito en el comentario anterior, el `if` queda mas sencillo y sin `null`
```suggestion
		if (existeCorreo) {
```

2021-03-05 19:43 UTC, Elsorbo commented on src/main/java/com/istb/app/services/profesor/ProfesorServiceImpl.java
>  		Profesor _profesor = profesorRepository.findById(id).orElse(null);
La gracia de utilizar Optional es no tener que tratar con valores `null`, ten en cuenta eso. Podrias devolver una nueva instancia de `Profesor` en lugar de `null`.

2021-03-05 19:43 UTC, Elsorbo commented on src/main/java/com/istb/app/services/profesor/ProfesorServiceImpl.java
> +		data.put("profesor", profesorGuarded.getId());
Deberías ponerle `profesorId` a la clave, para que en la plantilla no existan ambiguedades. Cuando ves el HTML;

`<a th:href="${url+'/verify/'+profesor+'/'+token}"`

la primera pregunta es ¿Que es `profesor`?, luego visitas este archivo y queda claro. Debes evitar, cuanto se pueda, que para entender una parte del código alguien viaje a otro archivo.

```suggestion
		data.put("profesorId", profesorGuarded.getId());
```
Asi el HTML queda mejor descrito: `<a th:href="${url+'/verify/'+profesorId+'/'+token}"`

2021-03-05 19:43 UTC, Elsorbo commented on src/main/java/com/istb/app/services/profesor/ProfesorServiceImpl.java
> +		Profesor profesorGuarded = profesorRepository.save(profesor);
Una solución rápida podria ser definirle una contraseña y adjuntarsela en el correo. Buena observación @jorgdz .

2021-03-05 19:43 UTC, Elsorbo commented on src/main/resources/static/js/perfil/upload-image.js
> +);
Trata de usar `let` en lugar de `var`.

Razones: 
- [Diferencias entre var y let](https://www.analyticslane.com/2019/06/10/diferencias-entre-var-y-let-en-javascript/) 
- [Mozila Developer Network Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let)

2021-03-06 02:49 UTC, Elsorbo commented on src/main/resources/static/js/perfil/upload-image.js
> +		var formData = new FormData();
Corrige este `var`
```suggestion
		let formData = new FormData();
```

2021-03-06 06:57 UTC, jorgdz approved these changes

2021-03-08 01:04 UTC, Elsorbo approved these changes

2021-03-08 01:15 UTC, merged